'use strict';
const kind=document.body.dataset.kind,interview=kind==='interview',key='linux-learning-'+kind+'-v1';
const $=s=>document.querySelector(s);const make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
let saved=new Set(),theme='dark',lang='en';
try{const raw=localStorage.getItem(key);if(raw&&raw.length<12000){const s=JSON.parse(raw);if(Array.isArray(s.saved))saved=new Set(s.saved.filter(v=>typeof v==='string'&&DATA.some(d=>d.id===v)));if(s.theme==='light')theme='light';if(s.lang==='hi')lang='hi'}}catch{}
function store(){try{localStorage.setItem(key,JSON.stringify({saved:[...saved],theme,lang}))}catch{$('#status').textContent='Browser storage unavailable. Changes work for this visit only.'}}
function appearance(){document.body.classList.toggle('light',theme==='light');$('.theme').textContent=theme==='light'?'Dark mode':'Light mode';$('.lang').textContent=lang==='hi'?'English tips':'Hinglish tips';$('#guidance').textContent=lang==='hi'?'Practice disposable Linux lab me karo. File path, package aur service naam apni machine par check karo. Yahan koi command execute nahi hoti.':'Use a disposable Linux lab for practice. Examples may need files, packages or services that exist on your machine. Nothing executes here.'}
$('.theme').addEventListener('click',()=>{theme=theme==='dark'?'light':'dark';appearance();store()});$('.lang').addEventListener('click',()=>{lang=lang==='en'?'hi':'en';appearance();store()});appearance();
let view='learn',topic='all',limit=12;function sourceLink(url){let u;try{u=new URL(url)}catch{return make('span','Reference unavailable','source')}if(u.protocol!=='https:')return make('span','Reference unavailable','source');const a=make('a','Read reference ↗','source');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';return a}
function render(){const list=$('#cards');list.replaceChildren();const q=$('.search').value.trim().toLowerCase();const level=$('#level')?.value,impact=$('#impact')?.value;
const rows=DATA.filter(d=>(topic==='all'||d.topic===topic)&&(view!=='saved'||saved.has(d.id))&&(level==='All'||!level||d.level===level)&&(!impact||impact==='All'||(impact==='Read-only'?d.risk==='Read-only':d.risk!=='Read-only'))&&JSON.stringify(d).toLowerCase().includes(q));$('#count').textContent=rows.length+' entries';$('#sectiontitle').textContent=view==='saved'?'Your saved entries':interview?'Start with the essentials':'Commands worth knowing';
if(!rows.length)list.append(make('p','No matching entries. Change your search or filters.','empty'));
for(const d of rows.slice(0,limit)){const card=make('article',undefined,'card');card.dataset.id=d.id;const meta=make('div',undefined,'meta');meta.append(make('span',d.topic.toUpperCase()),make('span',interview?d.level:d.platform,'pill'));card.append(meta);const h=make('h3');
if(interview){const b=make('button',d.title,'question');b.setAttribute('aria-expanded','false');const a=make('div',undefined,'answer');a.hidden=true;a.append(make('p',d.answer),make('code',d.example,'code'),sourceLink(d.source));for(const u of d.additionalSources||[])a.append(sourceLink(u));b.addEventListener('click',()=>{a.hidden=!a.hidden;b.setAttribute('aria-expanded',String(!a.hidden))});h.append(b);card.append(h,make('p','Tap the question to read the answer and example.'),a)}else{h.textContent=d.name;card.append(h,make('p',d.description),make('code',d.example,'code'),make('p',d.flags),make('div',d.note,'hint'),make('p','Impact: '+d.risk,'risk'),sourceLink(d.source))}
const actions=make('div',undefined,'actions');const save=make('button',saved.has(d.id)?'Saved ★':'Save ☆','detail');save.setAttribute('aria-pressed',String(saved.has(d.id)));save.addEventListener('click',()=>{saved.has(d.id)?saved.delete(d.id):saved.add(d.id);store();render()});const copy=make('button','Copy example','detail');copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(d.example);$('#status').textContent='Example copied. Check paths and impact before running.'}catch{$('#status').textContent='Clipboard unavailable. Select the example text to copy.'}});actions.append(save,copy);card.append(actions);list.append(card)}$('#more').hidden=rows.length<=limit;
}
$('#more').addEventListener('click',()=>{limit+=12;render()});$('.search').addEventListener('input',()=>{limit=12;render()});$('.cta').addEventListener('click',()=>{setView('learn');$('.search').focus()});document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>{topic=b.dataset.topic;document.querySelectorAll('[data-topic]').forEach(n=>n.classList.toggle('active',n===b));limit=12;render()}));$('#level')?.addEventListener('change',()=>{limit=12;render()});$('#impact')?.addEventListener('change',()=>{limit=12;render()});
function setView(v){view=v;const learn=v==='learn'||v==='saved';$('#filters').hidden=!learn;$('#cards').hidden=!learn;$('#more').hidden=!learn;$('#quiz').hidden=v!=='quiz';$('#sources').hidden=v!=='sources';$('#sectiontitle').hidden=!learn;$('#count').hidden=!learn;$('#status').textContent='';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===v));if(learn)render();else if(v==='quiz')$('#more').hidden=true;else{const s=$('#sources');s.replaceChildren(make('h2','Reference sources'),make('p','Original learning summaries with per-entry references. Documentation reviewed 8 October 2026; installed versions can differ.'));for(const u of [...new Set(DATA.map(d=>d.source))]){const a=sourceLink(u);a.textContent=u;s.append(a)}}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#clear').addEventListener('click',()=>{if(confirm('Clear bookmarks and theme/language settings for this site?')){saved.clear();theme='dark';lang='en';try{localStorage.removeItem(key)}catch{}appearance();setView('learn');$('#status').textContent='Local data cleared.'}});
let questions=[],index=0,score=0;const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};function startQuiz(){questions=shuffle(DATA.filter(d=>d.choices)).slice(0,Number($('#quizcount').value));index=0;score=0;quizRender()}
function quizRender(){const box=$('#quizbody');box.replaceChildren();if(index>=questions.length){box.append(make('h2','Quiz complete'),make('p',score+' / '+questions.length+' correct. Review the explanations and try again.'));return}const d=questions[index],card=make('article',undefined,'card');card.append(make('div','Question '+(index+1)+' / '+questions.length+' · '+d.topic,'meta'),make('h3',d.title));const explanation=make('div');explanation.hidden=true;let answered=false;for(const opt of shuffle(d.choices)){const b=make('button',opt,'quizoption');b.addEventListener('click',()=>{if(answered)return;answered=true;const correct=opt===d.choices[0];if(correct)score++;card.querySelectorAll('.quizoption').forEach(n=>{n.disabled=true;if(n.textContent===d.choices[0])n.classList.add('correct');else if(n===b)n.classList.add('wrong')});explanation.append(make('p',correct?'Correct.':'Not quite. The green choice is correct.'),make('p',d.answer),make('code',d.example,'code'),sourceLink(d.source));const next=make('button',index+1===questions.length?'Show score':'Next question','cta');next.addEventListener('click',()=>{index++;quizRender()});explanation.append(next);explanation.hidden=false});card.append(b)}card.append(explanation);box.append(card)}$('#startquiz')?.addEventListener('click',startQuiz);
{const s1=document.getElementById('stat1'),s2=document.getElementById('stat2');if(s1&&s2){if(interview){s1.textContent=DATA.filter(d=>!d.choices).length;s2.textContent=DATA.filter(d=>d.choices).length}else{s1.textContent=DATA.length;const ex=new Set();for(const d of DATA){ex.add(d.example);for(const m of d.flags.matchAll(/\(e\.g\. ([^)]+)\)/g))ex.add(m[1])}s2.textContent=ex.size}}}
render();
